import React from 'react';

const About = () => {
    return (
        <div className="about">
            <h1 className="text-center p-3 bg-white">About us</h1>
            <p className="p-5 bg-white">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti expedita quia, sapiente qui harum labore laborum, nesciunt maiores aliquid a fuga, incidunt nisi nobis natus est! Ipsam voluptatibus fugiat placeat? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti expedita quia, sapiente qui harum labore laborum, nesciunt maiores aliquid a fuga, incidunt nisi nobis natus est! Ipsam voluptatibus fugiat placeat?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti expedita quia, sapiente qui harum labore laborum, nesciunt maiores aliquid a fuga, incidunt nisi nobis natus est! Ipsam voluptatibus fugiat placeat?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti expedita quia, sapiente qui harum labore laborum, nesciunt maiores aliquid a fuga, incidunt nisi nobis natus est! Ipsam voluptatibus fugiat placeat?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti expedita quia, sapiente qui harum labore laborum, nesciunt maiores aliquid a fuga, incidunt nisi nobis natus est! Ipsam voluptatibus fugiat placeat?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti expedita quia, sapiente qui harum labore laborum, nesciunt maiores aliquid a fuga, incidunt nisi nobis natus est! Ipsam voluptatibus fugiat placeat?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti expedita quia, sapiente qui harum labore laborum, nesciunt maiores aliquid a fuga, incidunt nisi nobis natus est! Ipsam voluptatibus fugiat placeat?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti expedita quia, sapiente qui harum labore laborum, nesciunt maiores aliquid a fuga, incidunt nisi nobis natus est! Ipsam voluptatibus fugiat placeat?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti expedita quia, sapiente qui harum labore laborum, nesciunt maiores aliquid a fuga, incidunt nisi nobis natus est! Ipsam voluptatibus fugiat placeat?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti expedita quia, sapiente qui harum labore laborum, nesciunt maiores aliquid a fuga, incidunt nisi nobis natus est! Ipsam voluptatibus fugiat placeat?</p>
        </div>
    );
};

export default About;